const SET_SIGNED_IN = 'SET_SIGNED_IN';
const SET_USER_DETAILS = 'SET_USER_DETAILS';
const SET_ORG_UNIT_DETAILS = 'SET_ORG_UNIT_DETAILS';
const SET_BADGE_NUMBER = 'SET_BADGE_NUMBER';
const SET_CUSTOMER = 'SET_CUSTOMER';
const CLEAR_CUSTOMER = 'CLEAR_CUSTOMER';
const DISABLE_DRAWER = 'DISABLE_DRAWER';
const SET_COUPONS = 'SET_COUPONS';

export {
    SET_SIGNED_IN,
    SET_USER_DETAILS,
    SET_ORG_UNIT_DETAILS,
    SET_BADGE_NUMBER,
    SET_CUSTOMER,
    CLEAR_CUSTOMER,
    DISABLE_DRAWER,
    SET_COUPONS
};